name: React.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.19.6] # Updated to match your local v20.19.6

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile  
    
    - name: Setup Environment
      run: |
        touch .env
        echo '${{ secrets.PROCLIENT360_FRONT_ENV }}' > .env
        
    - name: Build the project
      run: CI=false yarn build --if-present

    - name: Deploy to Nginx Folder
      # This moves the files to where your website actually lives
      run: |
        sudo  mkdir -p /home/vicky/ProClient360/pms-front/build
        sudo rm -rf /home/vicky/ProClient360/pms-front/build/*
        sudo cp -r build/* /home/vicky/ProClient360/pms-front/build/
        sudo chown -R vicky:vicky /home/vicky/ProClient360/pms-front/build  GNU nano 8.2                                                  .github/workflows/node.js.yml                                                  Modified
jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.19.6] # Updated to match your local v20.19.6

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Setup Environment
      run: |
        touch .env
        echo '${{ secrets.PROCLIENT360_FRONT_ENV }}' > .env

    - name: Build the project
      run: CI=false yarn build --if-present

    - name: Deploy to Nginx Folder
      # This moves the files to where your website actually lives
      run: |
        sudo  mkdir -p /home/vicky/ProClient360/pms-front/build
        sudo rm -rf /home/vicky/ProClient360/pms-front/build/*
        sudo cp -r build/* /home/vicky/ProClient360/pms-front/build/
        sudo chown -R vicky:vicky /home/vicky/ProClient360/pms-front/build
